### ISSUE TITLE
[Web Service, POST] Melakukan Peminjaman Ruangan Meeting ke SI-Ruangan

### ISSUE THREAD

**Issue by farril-zavier** [farril-zavier/TA_C_5#15]
Koperasi sebelum melakukan pertemuan rutin pengurus selalu melakukan peminjaman tempat. Pada fitur ini anda diminta untuk menyediakan web service untuk melakukan peminjaman ruangan (merujuk pada fitur Mengajukan Peminjaman Ruangan pada SI-Ruangan). Fitur ini hanya dapat diakses oleh Pengurus Koperasi (user/role ini digunakan sebagai pengganti jika dibutuhkan pada SI-Ruangan).

**Comment by romihadiyan** [comment]
done
