### ISSUE TITLE
Menambah Anggota

### ISSUE THREAD

**Issue by nadhirashafa** [farril-zavier/TA_C_5#4]
Pada fitur ini Anda diminta untuk membuat fungsi menambah anggota. Fitur ini hanya dapat diakses oleh Pengurus Koperasi (lihat tabel role) serta memiliki halaman tersendiri. Halaman berisi form untuk memasukkan data anggota dan tombol submit. Jika tombol submit diklik, maka sistem akan melakukan verifikasi apakah anggota dengan nia yang sama sudah ada atau belum pada database. Jika belum ada, maka data anggota dimasukkan kedalam database lalu tampilkan konfirmasi sukses. Jika sudah ada, maka sistem menampilkan konfirmasi gagal.
Form pada halaman ini terdiri dari:
- Nama
- KTP
- Tempat Lahir
- Tanggal Lahir
- Alamat
- Telepon
- Pengurus (Ya (1) dan Tidak (0), menggunakan dropdown)
Atribut NIA diisi dengan delapan digit random number yang unik
**Web Service SI-Ruangan**: Pada saat menambah anggota, Anda perlu mengambil data fasilitas koperasi dengan menggunakan method GET. Ini dilakukan untuk mengecek apakah fasilitas koperasi dapat mangakomodir anggota baru tersebut jika ingin diangkat menjadi pengurus. Jika jumlah pengurus saat ini melebihi jumlah kursi (ruang koperasi), maka isian data Pengurus pada form, pilihan dropdown Ya (1) menjadi tidak ada (hilang). Dengan kata lain anggota baru tersebut tidak bisa diangkat menjadi pengurus

**Comment by romihadiyan** [comment]
done ya
