### ISSUE TITLE
Mengubah Status Keanggotaan

### ISSUE THREAD

**Issue by nadhirashafa** [farril-zavier/TA_C_5#6]
Pada fitur ini Anda diminta untuk membuat fungsi mengubah status keanggotaan (atribut is_pengurus). Fitur ini hanya dapat diakses oleh Pengurus Koperasi (lihat tabel role). Anda dibebaskan dalam mengimplementasikan fitur ini.

**Comment by romihadiyan** [comment]
I have finished this feature.
